// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2PJeQnTNLhFHnJGsvlJ0fgwFq6Z-hE8',
    appId: '1:895316073814:web:31cd611abfe3cd6a168af7',
    messagingSenderId: '895316073814',
    projectId: 'investden-b16fa',
    authDomain: 'investden-b16fa.firebaseapp.com',
    storageBucket: 'investden-b16fa.firebasestorage.app',
    measurementId: 'G-LK1T3V9DCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPy6MlbY31U_rNLs9zqjAPuL6FPKAD-NQ',
    appId: '1:895316073814:android:5b1ec389301a1566168af7',
    messagingSenderId: '895316073814',
    projectId: 'investden-b16fa',
    storageBucket: 'investden-b16fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEGg-RBmaiw4VCxMQnDQ6JlYDvCyKkOE',
    appId: '1:895316073814:ios:96956392487e2745168af7',
    messagingSenderId: '895316073814',
    projectId: 'investden-b16fa',
    storageBucket: 'investden-b16fa.firebasestorage.app',
    iosBundleId: 'com.example.investden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVEGg-RBmaiw4VCxMQnDQ6JlYDvCyKkOE',
    appId: '1:895316073814:ios:96956392487e2745168af7',
    messagingSenderId: '895316073814',
    projectId: 'investden-b16fa',
    storageBucket: 'investden-b16fa.firebasestorage.app',
    iosBundleId: 'com.example.investden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR2PJeQnTNLhFHnJGsvlJ0fgwFq6Z-hE8',
    appId: '1:895316073814:web:324d12dcc2ce8a27168af7',
    messagingSenderId: '895316073814',
    projectId: 'investden-b16fa',
    authDomain: 'investden-b16fa.firebaseapp.com',
    storageBucket: 'investden-b16fa.firebasestorage.app',
    measurementId: 'G-8CW8BRR66Q',
  );
}
